### ISSUE TITLE
Error with backend MPI

### ISSUE THREAD

**Issue by JiakunYan** [berkeley-container-library/bcl-docker#1]
When running
`cd src/bcl/examples/simple`
`make`
`mpirun -n 2 hello_world`
the following error appears
> It appears as if there is not enough space for /dev/shm/osc_rdma.03b00fd756c5.afa20001.3 (the shared-memory backing
file). It is likely that your MPI job will now either abort or experience
performance degradation.
>
>  Local host:  03b00fd756c5
>  Space Requested: 536871656 B
>  Space Available: 64798720 B

and then the program is stuck

**Comment by BenBrock** [comment]
What happens if you try adding `--shm-size=1024M` (or some larger number)?

I'm assuming this is with the `release` Dockerfile?

**Comment by JiakunYan** [comment]
Yeah this is with the `release` Dockerfile.
There is no `--shm-size` option in mpirun

**Comment by BenBrock** [comment]
No, when you create the docker container you need to pass it a `--shm-size` option.

The issue is caused by there not being enough shared memory inside the Docker container, but you can increase the amount with this command line option.

**Comment by JiakunYan** [comment]
That fixes the problem. Thanks!

**Comment by SeyedMir** [comment]
I'm running into the same issue when switching from MPICH to Open MPI.
1. Why does ompi need 512M shared memory under `/dev/shm`?
2. Is there any other way to avoid this issue? other than increasing the container's shared memory size?
3. Is this expected to happen even when `OMPI_MCA_btl=^sm`?

**Comment by BenBrock** [comment]
> 1. Why does ompi need 512M shared memory under /dev/shm?

BCL allocates a fixed-size window of pinned remote memory at initialization.  The amount is controllable by passing a different value to `BCL::init()`, but by default I believe this is 256M (thus when within a single node, you'd need 512M available for 2 processes, 1024M for 4, etc.).

Essentially, if you're using the MPI backend, each process is going to call `MPI_Win_allocate` during `BCL::init()` (SHMEM will call `shmem_malloc`, etc.).  Depending on your MPI implementation, this will do different things.  For Open MPI within a single node, they have a POSIX shared memory backend, which is ultimately what you want.  This under the hood will use `shm_open` and `shmat` to create a POSIX shared memory window shared by all the processes.  POSIX shared memory windows are exposed using the filesystem (even though they're backed by raw memory), which is restricted inside of Docker.  I'm not sure precisely how it's configured, but you need to explicitly give Docker more space for POSIX shared memory using `--shm-size`.

> 2. Is there any other way to avoid this issue? other than increasing the container's shared memory size?

It's possible that another Open MPI conduit might not use POSIX shared memory windows and thus not need `/dev/shm` in your container, but I'm not sure. POSIX shared memory will by far give you the best performance, so that's probably what you want.

Different MPI implementations implement MPI one-sided RMA in different ways.  Pure MPICH just emulates it with message passing.  Instead of using shared memory, processes send messages back and forth to emulate one-sided remote memory accesses.  This is why there's no issue with MPICH---it's using IPC, not shared memory.  This can really be quite slow, but it's very portable, which is pure MPICH's goal.

> 3. Is this expected to happen even when OMPI_MCA_btl=^sm?

It's been a while since I've looked at Open MPI conduits, but my guess is that `^sm?` is meant to be POSIX shared memory windows, which would use precisely the mechanism I described above.  So, yes, this would be the expected behavior.


Let me know if you have any more questions; also happy to chat.
